var select = document.getElementById("selectColor");
var options = ["Adventure Green", "Adventure Green Melange","Anthracite Melange","After Dark","Art Green", "Anthra", "Aubergine","Aqua","Azur","Azurblå","Anthrazt","Bark","Bark Green","Beech Green","Beluga","Black ink", "Blue check","Blue Check", "Bronze", "Brown Check", "BrownLeaf", "BrownLeafMelange", "Buckthorn", "Burnt Orange","Canteen","Cloudberry","CognacBrown","Cypress","Cypress Camou","DarkAnthracite", "DarkElm","DarkGreymelange", "DarkOlive","DarkPrune","DarkSand","DeepGreen","Driftwood","Dusty Green", "Elmwood","Fallen Leaf", "Fallen Leaf/Black", "Forrest Night","GH Snow","Golden Oak","Grape Leaf","Graphite Blue", "Graphite Green Melange", "Green check", "Green Check", "Green/Brown Leaf", "Greyhound melange", "IN-EQ Camouflage", "Innovation Camouflage", "Innovation GH Blaze Camouflage", "Innovation GH Camouflage", "Iron melange", "Koksgrå","Moss Green", "Orange Check", "Orange GH Camo", "Otter Brown", "Oxblood Red", "PalmGreen", "Peat", "Raven","REALTREE ADAPT™","REALTREE EDGE®","REALTREE EDGE® ORANGE","REALTREE MAX-5®","REALTREE TIMBER™","REALTREE WAV3", "Red Check", "Space Green", "Tarmac Green", "Timber", "Turf", "Vintage Khaki","Walnut", "Natural", "Hvid","Sort","Æble","Bordeaux","Beige","Brombær","Blå","Flaskegrøn","Brun","Bergundy","Champagne","Choco","Chokolade","klar","Kobalt","Koral","Mørk","Mørkeblå","Evergreen","Grøn","Grå","Grå melange","Hot pink", "Indigo", "Karry","Khaki","Kit","Kiwi","Koks","Lavendel","Citron","Lys blå","Lyserød","Lilla","Lime","Broncerød", "Lys Pink","Marone","Mint","Mokka","Navy", "Oliven","Orange","Petrol","Pink","Rød","Rosa","Kongeblå","Sand","Sølvgrå","Taupe","Toffee Brown", "Turkis","Vanilla","Gul","Fuchsia","Grafit melange", "Forest green","Dark Oliven", "Denim","Ler","Natur hvid","Cupcake design","Fluorescerened Orange", "Flourescerened gul", "001","007","010","011","019","020","026","030","035","039","046","050","053","090","Black/White","DarkBrown/Sandstone","Hunter Green/Black","Dark Blue/Navy", "Chili","Red/Navy", "Carhartt Gold","BrigtOrange/HeatherGreen","Bright Lime","Bright Orange","Breen","Brow","Charcoal Heather", "Cobalt Blue","Dark Blue","DEEP WINE","Dark Green","Dark Brown","DUSK BLUE","Heather Gray", "IRON ORE", "Port","ROSESMOKE", "TARMAC","WINTERWHITE","384","432","442","608","825","247","647","DBL","DWD","PRT","BLK","BLM","BOG","CLH","BRN","HGY","DKB","DGR","NVY","379-Hvid","2079-sort","5320-grøn","7920-grå","53","167","16720","Grey Melange","Coral melange","Denim Melange","Cobolt",
"Green melange", "Bright Red","Bright Red/Multi","Black/Multi","Bright Blue","Rotal Blue","Neon Yellow","Dark Navy", "Neon Green", "Mørk Navy", "Blood orange","Royal","Blue Melange","Anthracite Blue Melange","Charcoal grey","Olive Green","French Blue","Burgundy/White","Frenchblue/White","Dark Indigo","Denim Blue","Denim Grey", "Blue oxford", "White Print","Bl.w.print", "Light grey","Light Pink","Neon Cerise","Peach","Light Blue","Light Green","Lemon","Bright Lilac","Sky Blue","Neon Orange","Red melange","Navy Melange","Pistol","Cobalt melange","Apple Green","Sand Melange","Brown Melange","Sea Blue Melange","Nougat Melange","Off White","Navymel","Sandmel","Cobolt blue","Denim Black","Den.B.print","Red Print","Silver Print","Black Print","Dark Navy Print","Pink/White","Dark Navy/White","Dark Navy/Red","Dark Navy/Royal","Black/Red","Black/LightGrey","Silver grey","Mørk bordeaux","Snow melange","Mocca","Cerise","Sort-Hvid","æblegrøn","Lyseblå","rasberry","Prym1 Slate grey","Prym1 Typhoon Turquise","Woodland","Prym1 Pink Out","Coffee","Sandy grey","Navy Blue", "Greyish Blue","Camel","italian Blue","Anthracite","Light grey glen check", "blue glen check","light grey mottled","blue mottled","Flintstone","LeafGreen","DarkGrey","Grape","10","21","38","Bourbon Gold","28","90","Oxblood","koksmelange","Pacificblue"];

for(var i = 0; i < options.length; i++) {
    var opt = options[i];
    var el = document.createElement("option");
    el.textContent = opt;
    el.value = opt;
    select.add(el);
}